###
GET https://jsonplaceholder.typicode.com/posts/
Accept: application/json

###
GET http://localhost:3000/api/heroes
Accept: application/json

###
DELETE http://localhost:3000/api/heroes/97e5caea-48ff-4ca9-b75e-80517ff6ee51
Accept: application/json

###
POST http://localhost:3000/api/heroes
Content-Type: application/json
Accept: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "knownAs": "JD",
  "house": "Florida"
}

###
PUT http://localhost:3000/api/heroes/0439f4ad-5923-465a-99b6-73efe32db266
Content-Type: application/json

{
  "id": "0439f4ad-5923-465a-99b6-73efe32db266",
  "firstName": "John - Updated",
  "lastName": "Doe - Updated",
  "knownAs": "JD - Updated",
  "house": "Florida - Updated"
}

