###
GET http://localhost:3000/api/players
Accept: application/json

###
DELETE http://localhost:3000/api/players/4893hfwuig
Accept: application/json

###
POST http://localhost:3000/api/players
Content-Type: application/json
Accept: application/json

{
  "name": "Dev1",
  "mobile": "3543234",
  "email": "dev@facebook.no",
  "company": "Meta",
  "points": 50
}

###
PUT http://localhost:3000/api/heroes/67gi7fro67rf
Content-Type: application/json

{
  "id": "67gi7fro67rf",
  "name": "Dev2",
  "mobile": "23423422",
  "email": "dev2@aws.no",
  "company": "Amazon",
  "points": 50
}

