name: Build and deploy Node.js app to Azure Web App - scoreboard-inmeta-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  COSMOS_ENDPOINT: ${{secrets.COSMOS_ENDPOINT}}
  COSMOS_KEY: ${{secrets.COSMOS_KEY}}
  COSMOS_DATABASE_ID: ${{secrets.COSMOS_DATABASE_ID}}
  COSMOS_CONTAINER_ID: ${{secrets.COSMOS_CONTAINER_ID}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'scoreboard-inmeta-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_623036A33C1346AFADF698018069D3BF }}
          package: .
